In [1]:
%timeit [j**4 for j in range(1, 9)]

1.21 µs ± 13.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating Numpy Array 

In [46]:
import numpy as np
a = np.array([1,2, 3, 4])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [7]:
li = []

for i in range(1, 5):
    var = int(input("enter : "))
    li.append(var)
    
print(np.array(li))    

enter : 10
enter : 11
enter : 12
enter : 13
[10 11 12 13]


In [9]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [10]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [11]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zero array 

In [13]:
zeroArr = np.zeros(4)
zeroArr1 = np.zeros((3,4))

print(zeroArr)
print()
print(zeroArr1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones Array

In [14]:
oneAr = np.ones(4)
onearr = np.ones((3,4))
print(oneAr)
print()
print(onearr)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty Array

In [15]:
empAr = np.empty(4)
print(empAr)

[1. 1. 1. 1.]


# Range Array

In [16]:
arr = np.arange(4)
print(arr)

[0 1 2 3]


# Identity - Diagonal filled with one

In [17]:
ard = np.eye(3)
print(ard)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
ardd = np.eye(3, 5)
print(ardd)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Spaced linearly

In [20]:
arrs = np.linspace(0,20, num = 5)
print(arrs)

[ 0.  5. 10. 15. 20.]


# Random number Arrays

In [21]:
# rand() - 0-1
ra = np.random.rand(4)
print(ra)

[0.58333122 0.98968167 0.67326496 0.2643293 ]


In [22]:
ran = np.random.rand(2,5)
print(ran)

[[0.54539156 0.61191224 0.34530243 0.54580997 0.68878966]
 [0.97008708 0.62805248 0.87689042 0.51959541 0.41522813]]


In [23]:
# randn() close to 0 +- 
ra2 = np.random.randn(4)
print(ra2)

[-1.80282355 -0.12316954  1.11488907 -1.80999538]


In [24]:
ra3 = np.random.randn(2,4)
print(ra3)

[[-1.78531615  0.22002518 -2.04870593  0.12150782]
 [ 1.41771167 -0.71235214 -0.8575585   0.34149091]]


In [25]:
# ranf() [0.0, 1)
rf = np.random.ranf(4)
print(rf)

[0.98848183 0.77787    0.92934278 0.3161102 ]


In [26]:
# randint(min, max, noOfValues)
rn = np.random.randint(5,20,5)
print(rn)

[ 8  7  5  8 14]


# Datatypes in numpy array

In [27]:
dt = np.array([1,2,3,4])
print("Datatype : " , dt.dtype)

Datatype :  int64


In [31]:
dt1 = np.array([1,2,3,4,11,12,13,14,15,1333])
print("Datatype : " , dt1.dtype)

Datatype :  int64


In [32]:
dt2 = np.array([1,2.0,3,4.0])
print("Datatype : " , dt2.dtype)

Datatype :  float64


In [33]:
dt2 = np.array(["A","B","C","D"])
print("Datatype : " , dt2.dtype)

Datatype :  <U1


In [34]:
dt2 = np.array(["A","B","C","D",1,2,3,3])
print("Datatype : " , dt2.dtype)

Datatype :  <U21


In [37]:
x = np.array([1,2,3,4], dtype = np.int8)
print("Datatype : " , x.dtype)

Datatype :  int8


In [38]:
x1 = np.array([1,2,3,4], dtype = "f")
print("Datatype : " , x1.dtype)
print(x1)

Datatype :  float32
[1. 2. 3. 4.]


In [39]:
x2 = np.array([1,2,3,4])
xnew = np.float32(x2)
print("Datatype : " , x2.dtype)
print("Datatype : " , xnew.dtype)
print(x2)
print(xnew)

Datatype :  int64
Datatype :  float32
[1 2 3 4]
[1. 2. 3. 4.]


In [40]:
x3 = np.array([1,2,3,4])
newx3 = x3.astype(float)
print(x3)
print(newx3)

[1 2 3 4]
[1. 2. 3. 4.]


# Arithmetic Operation In Array

In [42]:
varr = np.array([1,2,3,4])
varadd =  varr + 3 
print(varadd)

[4 5 6 7]


In [44]:
varr1 = np.array([1,2,3,4])
varr2 = np.array([1,2,3,4])
varadd1 =  varr1 + varr2
print(varadd1)

[2 4 6 8]


In [50]:
varr1 = np.array([1,2,3,4])
varr2 = np.array([1,2,3,4])
varad = np.add(varr1, varr2)
print(varad)

[2 4 6 8]


In [45]:
varadd2 =  varr1 - 3
print(varadd2)

[-2 -1  0  1]


In [47]:
varadd2 =  varr1 * 3
print(varadd2)

[ 3  6  9 12]


In [48]:
varadd2 =  varr1 / 3
print(varadd2)

[0.33333333 0.66666667 1.         1.33333333]


In [49]:
varadd2 =  varr1 % 3
print(varadd2)

[1 2 0 1]


# 2D Array 

In [51]:
varr2D = np.array([[1,2,3,4],[5,6,7,8]])
varr22D = np.array([[1,2,3,4],[5,6,7,8]])
varadd =  np.add(varr2D, varr22D) 
print(varadd)

[[ 2  4  6  8]
 [10 12 14 16]]


# Broadcasting in Numpy 

In [2]:
a = np.array([1,2,3,4])
b = np.array([1,2,3])
print( a + b )

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [6]:
#  same dimension 
c = np.array([1,2,3])
print(c)
print()
d = np.array([[1],[2],[3]])
print(d)
print()
print(c + d)

[1 2 3]

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Indexing and Slicing 

In [11]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x[1::2])

[ 2  4  6  8 10]


In [12]:
y2d = np.array([[1,2,3,4],[5,6,7,8]])
print(y2d[1,1:])

[6 7 8]


# Iteration in Numpy

In [13]:
g = np.array([1,2,3,4,5,6,7,8,9,10])
for i in g:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [14]:
y2d2 = np.array([[1,2,3,4],[5,6,7,8]])
print(y2d2)
print()

for j in y2d2:
    print(j)
    
print()

for k in y2d2:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [17]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

print()

for i in ar3:
    for j in i:
        for k in j:
            print(k)
            

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
#  use nditer function to iterate without using multiple for loop 

ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)
print()
for i in np.nditer(ar3):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)
print()
for i,d in np.ndenumerate(ar3):
    print(i,d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(0, 2, 0) 9
(0, 2, 1) 10
(0, 2, 2) 11
(0, 2, 3) 12


# Copy vs View 

In [25]:
g = np.array([1,2,3,4,5,6,7,8,9,10])
co = g.copy()
g[1]=40
print("g:", g)
print("co:", co)

g: [ 1 40  3  4  5  6  7  8  9 10]
co: [ 1  2  3  4  5  6  7  8  9 10]


In [26]:
g = np.array([1,2,3,4,5,6,7,8,9,10])
vi = g.view()
g[1]=40
print("g:", g)
print("vi:", vi)

g: [ 1 40  3  4  5  6  7  8  9 10]
vi: [ 1 40  3  4  5  6  7  8  9 10]


# Join and Split

In [29]:
j1 = np.array([1,2,3,4])
j2 = np.array([11,22,33,44])

ca = np.concatenate((j1,j2))
print(ca)

[ 1  2  3  4 11 22 33 44]


In [31]:
j21 = np.array([[1,2],[3,4]])
j22 = np.array([[11,22],[33,44]])
print(j21)
print()
print(j22)
print()
ca2 = np.concatenate((j21,j22), axis = 1)
print(ca2)

[[1 2]
 [3 4]]

[[11 22]
 [33 44]]

[[ 1  2 11 22]
 [ 3  4 33 44]]


In [37]:
j21a = np.array([1,2,3,4])
j22b = np.array([6,7,8,9])
print(j21a)
print()
print(j22b)
print()
ca2a = np.stack((j21a,j22b), axis = 1)
ca2a1 = np.hstack((j21a,j22b))
print(ca2a)
print()
print(ca2a1)

[1 2 3 4]

[6 7 8 9]

[[1 6]
 [2 7]
 [3 8]
 [4 9]]

[1 2 3 4 6 7 8 9]


In [38]:
ca2a2 = np.vstack((j21a,j22b))
ca2a3 = np.dstack((j21a,j22b))

print(ca2a2)
print(ca2a3)

[[1 2 3 4]
 [6 7 8 9]]
[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


# Split Array

In [41]:
sp = np.array([1,2,3,4,5,3,7,3,9])
print(sp)

spl = np.array_split(sp, 3)
print(spl)
print(type(spl))
print()
print(spl[1])

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>

[4 5 6]


# Numpy functions 

In [43]:
se = np.array([1,2,3,4,3,6,7,8,3])
val = np.where( se == 3 )
print(val)

(array([2, 4, 8]),)


In [45]:
ss = np.array([1,2,3,4,6,7,8])
ff = np.searchsorted(ss, 5)
print(ff)


4


# Insert

In [52]:
var = np.array([1,2,3,4,5])
print(var)
v = np.insert(var, 2, 40)
print(v)
v1 = np.insert(var, (2,4), 40.4)
print(v1)

[1 2 3 4 5]
[ 1  2 40  3  4  5]
[ 1  2 40  3  4 40  5]


In [58]:
var1 = np.array([[1,2],[3,4]])
v2 = np.insert(var1, 2, 6 , axis = 0)
print(v2)
print()
v3 = np.insert(var1, 2, [6,7] , axis = 0)
print(v3)

[[1 2]
 [3 4]
 [6 6]]

[[1 2]
 [3 4]
 [6 7]]


# Append

In [59]:
var3 = np.array([1,2,3,4,5])
v4 = np.append(var3, 6.6)
print(v4)


[1.  2.  3.  4.  5.  6.6]


In [64]:
var4 = np.array([[1,2],[3,4]])
v5 =  np.append(var4, [[6,4]], axis = 0)
print(v5)

[[1 2]
 [3 4]
 [6 4]]


# Delete 

In [65]:
var5 = np.array([1,2,3,4,5])
print(np.delete(var5, 2))

[1 2 4 5]
